package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;

@Tag("regression")
public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you ")
    @DisplayName("TemplateOne page opened")
    void generatedTest() {
        step("Открыть \"https://www.hopa.com/\"", () -> {
            step("Inside", () -> {
                step("Inside2.1", () -> {
                    open("https://www.hopa.com/");
                });
                step("Inside2.2", () -> {
                    open("https://www.hopa.com/");
                });
            });
        });

        step("Проверить URL", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://www.hopa.com/'", () ->
                open("https://www.hopa.com/"));

        step("Page title should have text 'Hopa Casino Online - spielen Sie die besten Online-Spiele mit einem 200 € Casino Bonus'", () -> {
            String expectedTitle = "Hopa Casino Online - spielen Sie die besten Online-Spiele mit einem 200 € Casino Bonus";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://www.hopa.com/'", () ->
                open("https://www.hopa.com/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}