package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Tags;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.webdriver;
import static com.codeborne.selenide.WebDriverConditions.url;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;

public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you ")
    @DisplayName("TemplateOne page opened")
    void generatedTest() {
        step("Открыть \"https://www.google.com/\"", () -> {

            open("https://www.google.com/");
        });

        step("Проверить URL", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://www.google.com/'", () ->
                open("https://www.google.com/"));
        webdriver().shouldHave(url("https://www.google.com/"));
    }

    @Test
    @Description("falseTest")
    @DisplayName("falseTest")
    void falseTest() {
        step("Open url 'https://www.google.com/'", () ->
                open("https://www.google.com/"));
        webdriver().shouldHave(url("https://www.gooelrigle.com/"));
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://www.google.com/'", () ->
                open("https://www.google.com/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}